/*
 * imap_err.h:
 * This file is automatically generated; please do not edit it.
 */

#ifndef __ERROR_TABLE_imap_H__
#define __ERROR_TABLE_imap_H__

#ifdef __cplusplus
extern "C" {
#endif

extern const struct error_table et_imap_error_table;

#define initialize_imap_error_table()

#define IMAP_INTERNAL                            (2390157824L)
#define IMAP_IOERROR                             (2390157825L)
#define IMAP_SYS_ERROR                           (2390157826L)
#define IMAP_NOSPACE                             (2390157827L)
#define IMAP_PERMISSION_DENIED                   (2390157828L)
#define IMAP_QUOTA_EXCEEDED                      (2390157829L)
#define IMAP_MESSAGE_TOO_LARGE                   (2390157830L)
#define IMAP_USERFLAG_EXHAUSTED                  (2390157831L)
#define IMAP_NAMESPACE_BADPREFIX                 (2390157832L)
#define IMAP_MAILBOX_BADFORMAT                   (2390157833L)
#define IMAP_MAILBOX_CRC                         (2390157834L)
#define IMAP_MAILBOX_NOTSUPPORTED                (2390157835L)
#define IMAP_MAILBOX_NONEXISTENT                 (2390157836L)
#define IMAP_MAILBOX_EXISTS                      (2390157837L)
#define IMAP_MAILBOX_BADNAME                     (2390157838L)
#define IMAP_MAILBOX_MOVED                       (2390157839L)
#define IMAP_MAILBOX_RESERVED                    (2390157840L)
#define IMAP_MAILBOX_LOCKED                      (2390157841L)
#define IMAP_PARTITION_UNKNOWN                   (2390157842L)
#define IMAP_INVALID_IDENTIFIER                  (2390157843L)
#define IMAP_MESSAGE_CONTAINSNULL                (2390157844L)
#define IMAP_MESSAGE_CONTAINSNL                  (2390157845L)
#define IMAP_MESSAGE_CONTAINS8BIT                (2390157846L)
#define IMAP_MESSAGE_BADHEADER                   (2390157847L)
#define IMAP_MESSAGE_NOBLANKLINE                 (2390157848L)
#define IMAP_QUOTAROOT_NONEXISTENT               (2390157849L)
#define IMAP_PROTOCOL_ERROR                      (2390157850L)
#define IMAP_PROTOCOL_BAD_PARAMETERS             (2390157851L)
#define IMAP_ANNOTATION_BADENTRY                 (2390157852L)
#define IMAP_ANNOTATION_BADATTRIB                (2390157853L)
#define IMAP_ANNOTATION_BADVALUE                 (2390157854L)
#define IMAP_BADURL                              (2390157855L)
#define IMAP_ZERO_LENGTH_LITERAL                 (2390157856L)
#define IMAP_BAD_SERVER                          (2390157857L)
#define IMAP_SERVER_UNAVAILABLE                  (2390157858L)
#define IMAP_REMOTE_DENIED                       (2390157859L)
#define IMAP_AGAIN                               (2390157860L)
#define IMAP_NOT_SINGULAR_ROOT                   (2390157861L)
#define IMAP_REMOTE_NO_MULTIAPPEND               (2390157862L)
#define IMAP_UNRECOGNIZED_CHARSET                (2390157863L)
#define IMAP_INVALID_USER                        (2390157864L)
#define IMAP_INVALID_LOGIN                       (2390157865L)
#define IMAP_ANONYMOUS_NOT_PERMITTED             (2390157866L)
#define IMAP_UNSUPPORTED_QUOTA                   (2390157867L)
#define IMAP_SASL_FAIL                           (2390157868L)
#define IMAP_SASL_CANCEL                         (2390157869L)
#define IMAP_SASL_PROTERR                        (2390157870L)
#define IMAP_NO_OVERQUOTA                        (2390157871L)
#define IMAP_NO_CLOSEQUOTA                       (2390157872L)
#define IMAP_NO_MSGGONE                          (2390157873L)
#define IMAP_NO_CHECKSEEN                        (2390157874L)
#define IMAP_NO_CHECKPRESERVE                    (2390157875L)
#define IMAP_NO_NOSUCHMSG                        (2390157876L)
#define IMAP_NO_NOSUCHANNOTATION                 (2390157877L)
#define IMAP_NO_UNKNOWN_CTE                      (2390157878L)
#define IMAP_BYE_LOGOUT                          (2390157879L)
#define IMAP_OK_COMPLETED                        (2390157880L)
#define ERROR_TABLE_BASE_imap                    (2390157824L)

#ifdef __cplusplus
};
#endif

#endif /* __ERROR_TABLE_imap_H__ */
